[package]
name = "audio-replacer"
version = "5.0.0"
description = "Streamline audio dubbing"
authors = ["shob3r"]
edition = "2024"

[lib]
name = "audio_replacer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures-lite = "2.6.0"
users = "0.11.0"
tauri-plugin-os = "2"
tauri-plugin-http = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
walkdir = "2.5.0"
whisper-rs = { version = "0.14.2", features = ["vulkan"] }
hound = "3.5.1"
tauri-plugin-log = "2"
tauri-plugin-process = "2"
tauri-plugin-upload = "2"
tauri-plugin-store = "2"
