[package]
name = "audio_replacer"
version = "5.0.0"
description = "Easily dub video game voice-overs"
authors = ["Shob3r"]
edition = "2024"

[lib]
name = "audio_replacer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
tauri = { version = "2.5.1", features = ["protocol-asset"] }
tauri-plugin-opener = "2.3.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
futures-lite = "2.6.0"
tauri-plugin-os = "2.2.2"
tauri-plugin-http = "2.4.4"
tauri-plugin-fs = "2.3.0"
tauri-plugin-shell = "2.2.2"
walkdir = "2.5.0"
whisper-rs = { git = "https://github.com/ChakornK/whisper-rs", version = "0.14.3" } # This fork fixes an issue with audio transcription times taking 10x longer on release builds than on debug builds
hound = "3.5.1"
tauri-plugin-log = "2.5.0"
tauri-plugin-process = "2.2.2"
tauri-plugin-upload = "2.2.2"
tauri-plugin-store = "2.2.1"
tauri-plugin-dialog = "2.2.2"
tauri-plugin-drpc = "0.1.6"
num_cpus = "1.17.0"
pathdiff = "0.2.3"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2.2.1"
tauri-plugin-single-instance = "2.2.4"
