[package]
name = "audio_replacer"
version = "5.0.0"
description = " Easily dub over voicelines for video games"
authors = ["Shob3r"]
edition = "2021"

[lib]
name = "audio_replacer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures-lite = "2.6.0"
tauri-plugin-os = "2"
tauri-plugin-http = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
walkdir = "2.5.0"
whisper-rs = { git = "https://github.com/ChakornK/whisper-rs", version = "0.14.3" }
hound = "3.5.1"
tauri-plugin-log = "2"
tauri-plugin-process = "2"
tauri-plugin-upload = "2"
tauri-plugin-store = "2"
tauri-plugin-dialog = "2"
tauri-plugin-drpc = "0.1.6"
num_cpus = "1.17.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"
