name: audio-replacer
base: core22
version: '5.0.0'
summary: Streamline video game voice-over dubbing
description: |
  This app aims to make creating mods for video games that replace voicelines easier.

type: app
grade: stable
confinement: strict
source-code:
  - https://github.com/lemons-studios/audio-replacer

contact:
  - andrewpinter23@gmail.com

issues:
  - https://github.com/lemons-studios/audio-replacer/issues

compression: lzo

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  appname:
    command: usr/bin/audio-replacer
    desktop: usr/share/applications/audio-replacer.desktop
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
      - audio-record
    # Add whatever plugs you need here, see https://snapcraft.io/docs/snapcraft-interfaces for more info.
    # The gnome extension already includes [ desktop, desktop-legacy, gsettings, opengl, wayland, x11, mount-observe, calendar-service ]
    #  - single-instance-plug # add this if you're using the single-instance plugin
    #slots:
    # Add the slots you need to expose to other snaps
    #  - single-instance-plug # add this if you're using the single-instance plugin

# Add these lines only if you're using the single-instance plugin
# Check https://v2.tauri.app/plugin/single-instance/ for details
slots:
  single-instance:
    interface: dbus
    bus: session
    name: org.lemon-studios_audio-replacer.SingleInstance # Remember to change net_mydomain_MyApp to your app ID with "_" instead of "." and "-"

plugs:
  single-instance-plug:
    interface: dbus
    bus: session
    name: org.lemon-studios_audio-replacer.SingleInstance # Remember to change net_mydomain_MyApp to your app ID with "_" instead of "." and "-"

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
      - llvm
      - clang
      - cmake
      - jq
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu
      jq '.updater = {active: false} | del(.plugins.updater)' src-tauri/tauri.conf.json > src-tauri/new.json && mv -v src-tauri/new.json src-tauri/tauri.conf.json
      rustup default stable
      npm install
      npm run tauri build -- --bundles deb
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=appname|Icon=/usr/share/icons/hicolor/32x32/apps/appname.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/appname.desktop
